Fix NoMethodError printing nil in blue if there is no latest tag (#585)
```
❯ bin/release --type minor --debug --show-system-output
[runger_release_assistant] Running release with options {rubygems: true, tag_prefix: "gem/", type: "minor", debug: true, show_system_output: true}
[runger_release_assistant] You are running the release process with options {rubygems: true, tag_prefix: "gem/", type: "minor", debug: true, show_system_output: true}.
[runger_release_assistant] 

NoMethodError: undefined method 'blue' for nil
/home/david/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/runger_release_assistant-4.1.0/lib/runger_release_assistant.rb:105:in 'RungerReleaseAssistant#print_release_info'
/home/david/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/runger_release_assistant-4.1.0/lib/runger_release_assistant.rb:74:in 'RungerReleaseAssistant#run_release'
/home/david/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/runger_release_assistant-4.1.0/exe/release:51:in '<top (required)>'
bin/release:27:in 'Kernel#load'
bin/release:27:in '<main>'
```